IQTrading/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from  django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('news/', include('news.urls')),
    path('accounts/', include('accounts.urls')),
    path('analytics/', include('analytics.urls')),
    path('charts/', include('charts.urls')),
    path('blog/', include('blog.urls')),
    path('forum/', include('forum.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import index, start
# from .views import *

urlpatterns = [
    path('', index),
    path('index', index),
    path('blog', start),
]

news/urls.py
from django.urls import path, re_path
from .views import *


urlpatterns = [
    path('', catalog),
    path('catalog', catalog),
    path('add', add),
    path('add_ajax', add_ajax),
    re_path(r'^show/(?P<post_id>[0-9]+)$', show),
    re_path(r'^delete/(?P<post_id>[0-9]+)$', delete),
    re_path(r'^update/(?P<post_id>[0-9]+)$', update),
]


news/models.py
from django.db import models
from time import strftime


class Post(models.Model):
    topic = models.CharField(max_length=100, null=False)
    about = models.TextField(max_length=512, null=False)
    content = models.TextField(max_length=4096, null=False)
    image = models.FileField(null=False, upload_to='upload/')
    published = models.DateTimeField(null=False, default=strftime('%Y-%m-%d %H:%M:%S'))
    source = models.URLField(null=True)

    def __str__(self):
        return self.topic

news/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('topic', 'about', 'content', 'image', 'source')


class PostForm2(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('topic', 'about', 'content', 'source')



news/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, PostForm2
from .models import Post
from django.contrib.auth import logout
from django.core.paginator import Paginator
from .parser import get_html, get_link_head, get_link_content
from django.http import JsonResponse


def catalog(request):
    data = dict()
    data['title'] = 'List of News'
    all_posts = Post.objects.order_by('-id')
    data['posts'] = all_posts

    paginator = Paginator(all_posts, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    data['page_obj'] = page_obj
    return render(request, 'news/catalog.html', context=data)


def show(request, post_id):
    data = dict()
    data['title'] = 'Full view'
    data['post'] = Post.objects.get(id=post_id)
    return render(request, 'news/show.html', context=data)


def add(request):
    data = dict()
    data['parser_heads'] = get_link_head(get_html('https://www.finanz.ru/novosti'))
    data['title'] = 'New topic'
    # data['content'] = get_link_content(get_html(url))
    if request.method == 'GET':
        if request.user.username == 'admin' or 'superuser_iqtrading' or 'iadmin':
            data['form'] = PostForm(data=data)
            return render(request, 'news/add.html', context=data)
        else:
            logout(request)
            return redirect('/accounts/sign_in')
    elif request.method == 'POST':
        filled_form = PostForm(request.POST, request.FILES)
        filled_form.save()
        return redirect('/news')


def add_ajax(request):
    response = dict()
    link = request.GET.get('link')
    response['content'] = get_link_content(get_html(link))
    return JsonResponse(response)


def delete(request, post_id):
    data = dict()
    data['title'] = 'Remove new'
    post = Post.objects.get(id=post_id)
    if request.method == 'GET':
        if request.user.username == 'admin':
            data['post'] = post
            return render(request, 'news/delete.html', context=data)
        else:
            logout(request)
            return redirect('/accounts/sign_up')
    elif request.method =='POST':
        post.delete()
        return redirect('/news')
    

def update(request, post_id):
    data = dict()
    data['title'] = 'New`s topic'
    post = Post.objects.get(id=post_id)
    if request.method == 'GET':
        if request.user.username == 'admin':
            data['form'] = PostForm2(instance=post)
            data['post'] = post
            return render(request, 'news/update.html', context=data)
        else:
            logout(request)
            return redirect('/accounts/sign_up')
    elif request.method == 'POST':
        form2 = PostForm2(request.POST)
        if form2.is_valid():
            post.topic = form2.cleaned_data['topic']
            post.about = form2.cleaned_data['about']
            post.content = form2.cleaned_data['content']
            post.source = form2.cleaned_data['source']
            post.save()
        return redirect('/news')
            
def parser(request):
    pass

templates/news/add.html
{% extends "layout/base.html" %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div id="content" class="container">
    <div class="row">
        <div class="col-lg-6">
            <h3>{{ title }}</h3>
            <hr>
            <div style="text-align: left">
                <form method="post" action="/news/add" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="form_template">
                        {% for field in form %}
                            <div class="form-group">
                                {{ field.label_tag }}
                                <div>{{ field }}</div>
                            </div>
                        {% endfor %}
                    </div>
                    <p style="margin-top: 20px">
                        <input id="b1" type="submit" value="Send" class="btn btn-success">
                        <input id="b2" type="reset" value="Clear" class="btn btn-success">
                    </p>
                </form>
            </div>
            <a href="/news">Back</a>
        </div>
        <div class="col-lg-6">
            <h3>Parser</h3>
            <hr>
            <div style="text-align: left">
                <form method="post" action="/news/add" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div id="form_template2">
                        <label for="id_head">Head:</label>
                        <div class="form-group">
                            <select name="head" id="id_head">
                                {% for h in parser_heads %}
                                    <option value="{{ h.head.1 }}">{{ h.head.0 }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <label for="id_date">Date:</label>
                        <div class="form-group">
                            <input id="id_date" name="date" value="" type="text">
                        </div>
                        <label for="id_content1">Content:</label>
                        <div class="form-group">
                            <textarea name="content" id="id_content1" cols="40" rows="10"></textarea>
                            <script>CKEDITOR.replace( 'id_content' );</script>
                            <script>CKEDITOR.replace( 'id_content1' );</script>
                        </div>
                    </div>
                    <p style="margin-top: 20px">
                        <input id="b3" type="button" value="Fill Form" class="btn btn-primary btn">
                    </p>
                </form>
            </div>
        </div>
    </div>
    <hr>
</div>
<style>
    .form-group input, select {
        width: 100%;
        height: 30px;
    }
    .form-group textarea{
        width: 100%
    }
    #b1, #b2, #b3 {
        width: 150px
    }
</style>
<script src="https://code.jquery.com/jquery-latest.js"></script>
<script>
    $(document).ready(function () {
        $('#id_head').change(function () {
            CKEDITOR.instances.id_content1.setData("");
            //alert($("#id_head option:selected").text());
            $.ajax({
               url:"/news/add_ajax",
               data:"link="+$(this).val(),
               success:function(result){
                    //$("#id_content1").val(result.content);
                    //CKEDITOR.instances.id_content.insertText( result.content );
                    CKEDITOR.instances.id_content1.insertHtml( result.content );
                }
            });
        });
        $("#b3").click(function () {
            $("#id_topic").val($("#id_head option:selected").text());
                var fill = CKEDITOR.instances.id_content1.getData();
                //CKEDITOR.instances.id_content.insertText("fill");
                CKEDITOR.instances.id_content.insertHtml(fill);
        });
        $("#b2").click(function () {
            CKEDITOR.instances.id_content.setData("");
        });
    });
</script>
{% endblock content %}

templates/news/catalog.html
{% extends "layout/base.html" %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div id="content" class="container">
    <h3>{{ title }}</h3>
    <hr>
    {% if user.is_authenticated %}
        <a href="/news/add">Add news</a>
    {% endif %}
    <table class="news" border="1">
        <tr>
            <th>Image</th>
            <th>Topic</th>
            <th>About</th>
            <th>Published</th>
            <th>Source</th>
            <th>Manage</th>
        </tr>
        {% for post in page_obj %}
            <tr>
                <td>
                    <img src="/media/{{ post.image }}" width="100" height="50">
                </td>
                <td>{{ post.topic }}</td>
                <td>{{ post.about }}</td>
                <td>{{ post.published }}</td>
                <td>
                    <a href="{{ post.source }}" target="_blank">{{ post.source }}</a>
                </td>
                <td>
                    <a href="/news/show/{{ post.id }}">show</a>
                    {% if user.is_authenticated %}
                        <a href="/news/update/{{ post.id }}">update</a>
                        <a href="/news/delete/{{ post.id }}">delete</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <div class="pagination" style="margin-top: 20px">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last</a>
            {% endif %}
        </span>
    </div>
    <hr>
</div>
{% endblock content %}

templates/news/delete.html
{% extends "layout/base.html" %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div id="content" class="container">
    <h3>{{ title }}</h3>
    <hr>
    <h3>You are going to delete the new:</h3>
    <h3>{{ post.topic }}</h3>
    <h3>Confirm</h3>
    <form action="/news/delete/{{ post.id }}" method="post">
        {% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-secondary" style="width: 200px">
    </form>
    <hr>
    <a href="/news">Back to list of news</a>
</div>
{% endblock content %}

templates/news/show.html
{% extends "layout/base.html" %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div id="content" class="container">
    <h3>{{ title }}</h3>
    <hr>
    <div>
        <img src="/media/{{ post.image }}" width="30%" align="left" style="margin-right: 50px">
        <h3>{{ post.title }}</h3>
        <h5>{{ post.published }}</h5>
        <h4>{{ post.content }}</h4>
        <div style="clear: left"></div>
        <a href="/news">Bact to List of News</a>
    </div>
    <hr>
</div>
{% endblock content %}

templates/news/update.html
{% extends "layout/base.html" %}

{% block title %}{{ title }}{% endblock title %}


{% block content %}
<div id="content" class="container">
    <h3>{{ title }}</h3>
    <hr>
    <form id="postupdateform" method="post" action="/news/update/{{ post.id }}">
        {% csrf_token %}
        <div>
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    <div>
                        {{ field }}
                    </div>
                </div>
            {% endfor %}
        </div>
        <p style="margin-top: 30px">
            <input id="b1" type="submit" value="Save" class="btn btn-success">
            <input id="b2" type="reset" value="Clear" class="btn btn-success">
        </p>
    </form>
    <a href="/news">Bact to list of news</a>
    <hr>
</div>
<style>
    .form-group input {
        width: 50%;
        height: 30px;
    }
    .form-group textarea{
        width: 50%
    }
    #b1, #b2 {
        width: 150px
    }

</style>
{% endblock content %}